COMPONENT = "payment"
PROJECT_NAME = "roboshop"
PORT           = 8080
IAM_INSTANCE_PROFILE = true
SPOT_INSTANCE_COUNT = 0
INSTANCE_TYPE = "t2.micro"
INSTANCE_COUNT = 1
WORKSTATION_IP = "172.31.19.77/32"
